### ISSUE TITLE
feat(todo): priority todo list of minor tasks

### ISSUE THREAD

**Issue by kodemon** [sadoprotocol/sado-api#3]
General:

 - [ ] Signatures _Confirm if signatures is being validated_
 - [ ] Authenticated _incoming VS outgoing transaction direction_
 - [ ] Counts _Keep maker, taker, and location counts for each address within the order book?_

Order Specific:

 - [ ] Support for ordinal trading vs pay-for-inscription method

Offer Specific:

 - [x] Completed _List of confirmed transactions that took place_
